### ISSUE TITLE
usage of thread local

### ISSUE THREAD

**Issue by josh-devops-center** [jbalogh/django-multidb-router#22]
Hi,

The [masterdb pinning](https://github.com/jbalogh/django-multidb-router/blob/master/multidb/pinning.py) uses a thread local. In Django since a thread may outlive a request and threads may be reused between requests, there is a lack of thread safety and threadlocals are not recommended for use.

For the masterdb pinning, this may mean that queries which can query standby servers may instead query the master, and queries which should only query the master may query slaves.

I didn't find a disclaimer regarding this. I was wondering what sort of guarantees does multidb router provide?

Thanks

**Comment by jsocol** [comment]
multidb router was written with these constraints in mind. It is designed specifically [to handle the case where the thread is used for multiple requests](https://github.com/jbalogh/django-multidb-router/blob/master/multidb/middleware.py#L30-L38).

If you encounter issues where it fails, please let us know with specifics.

**Comment by josh-devops-center** [comment]
How does a cookie handle a request being reused? Multiple requests would overwrite each other.

**Comment by jsocol** [comment]
Please read the source code.

> Threads may be reused between requests.

Yes, and as I said, the package is _specifically designed to handle this_.  Cookies are sent—or not—by each individual client with each request.

If you are actually encountering errors, please open issues with specific details including how it's running (Apache/mod_wsgi, uwsgi, gunicorn, etc) and any relevant settings (e.g. number of processes/threads-per-process, etc).

**Comment by josh-devops-center** [comment]
So there are no test cases, just the fact that you say the design handles this?

**Comment by jsocol** [comment]
There are tests for this library. Not all deployments can be included in automated tests. Please file issues _if you encounter errors_.

I *strongly encourage* you to actually read the source code. I also encourage you to read up on HTTP cookies. Here is, briefly, how the library works:

The [middleware](https://github.com/jbalogh/django-multidb-router/blob/master/multidb/middleware.py) determines whether the request either (a) is not a "safe" method (GET, TRACE, OPTIONS, HEAD) or (b) includes a pinning cookie. If either is true, the thread is "pinned" to the master and all database reads are sent to the master. If neither is true, the library [explicitly "unpins" the thread](https://github.com/jbalogh/django-multidb-router/blob/master/multidb/middleware.py#L38), to solve the _exact_ issue you're describing (this is the code I linked earlier). An "unpinned" thread sends database reads to the read replicas.

The thread-local storage is used because the DB router does not have access to the current `HTTPRequest` object, so we need to store the pinned state somewhere we can guarantee the router can access.

A very common, and recommended, pattern after a `POST` request (e.g. creating a forum post) is to end it with a redirect to the new content, which causes a new `GET` request that will probably be handled by a different thread, if not a different host entirely. Cookies are used to ensure that users who just wrote content will read from the master for a few seconds (so their content will still be available even if there is some replication lag) regardless of how many requests they make or what hosts or threads serve those requests.

It is _certainly possible_ that there are bugs, particularly with gunicorn with gevent workers (though gevent should [patch `threading.local`](http://www.gevent.org/gevent.monkey.html#gevent.monkey.patch_thread) with everything else) or other green-thread solutions. If you experience bugs, please open issues. Otherwise, please read the source code if you want to know how something works.
